### ISSUE TITLE
stop.sh does not correctly kill server and picam

### ISSUE THREAD

**Issue by geefer** [iizukanao/picam-streamer#20]
The stop.sh within the script directory does not appear to correctly stop the node server or the picam process. This is independent of whether the script is run via "sudo service picam-streamer stop" or directly.

**Comment by iizukanao** [comment]
@Geefer Thank you for reporting the problem. Let me check.

**Comment by iizukanao** [comment]
@Geefer This bug has been fixed. Thank you for reporting the issue!
