### ISSUE TITLE
Possibility to rotate the screen

### ISSUE THREAD

**Issue by KarlBaumann** [iizukanao/picam-streamer#3]
I would like to rotate the screen, is it somehow possible?

**Comment by iizukanao** [comment]
Yes, [picam](https://github.com/iizukanao/picam) (the program that is internally used) supports `--rotation <degrees>` option.

For example, to rotate the video by 90 degrees clockwise, open /home/pi/picam-streamer/lib/server.js with a text editor and change the line 44 to:

```
picam = spawn('nice', ['-n', '-20', 'ionice', '-c1', '-n0', 'sudo', '-u', "#" + PICAM_UID, PICAM_PATH, '--rtspout', '--alsadev', 'hw:1,0', '--rotation', '90'], {
```

After the change, run `sudo service picam-streamer restart`, then reload the /view/ page.

**Comment by KarlBaumann** [comment]
thanks, it worked!
