### ISSUE TITLE
will picam-streamer work with raspberry pi 3 A+ model

### ISSUE THREAD

**Issue by rajeshkrarora1** [iizukanao/picam-streamer#32]

**Comment by iizukanao** [comment]
It should work.

**Comment by rajeshkrarora1** [comment]
sir,
 picam-streamer not working on raspberry pi 3 A+

**Comment by iizukanao** [comment]
Can you write down the details of the problem? Does standalone picam work on Pi 3 A+?

**Comment by rajeshkrarora1** [comment]
it's working for me now, thanks

**Comment by rajeshkrarora1** [comment]
thanks once again for this wonderful project
