### ISSUE TITLE
Using USB stick

### ISSUE THREAD

**Issue by ErHaMep** [iizukanao/picam-streamer#37]
Hi,

With the Raspbian desktop system I can access and use an usb stick as a storage device.
It is present in /media/pi/label.
But when I use the picam-streamer image I can not see the usb stick.
Is there a way to use an usb stick with picam-streamer?
Do I have to make an adjustment or must I mount the usb stick?

Thanks so far,
ErHaMep

**Comment by iizukanao** [comment]
Log in to your Raspberry Pi via ssh and mount the USB drive. Please see this guide. https://cialu.net/automount-external-usb-drive-raspberry-pi/

**Comment by ErHaMep** [comment]
Thanks.
I will try it.
ErHaMep
