### ISSUE TITLE
Instructions?

### ISSUE THREAD

**Issue by jpt000** [iizukanao/picam-streamer#40]
Picam-server works great out of the box. Nevertheless it would be nice to have a little more information, namely on how to change settings. Took me a couple of hours to figure out where to look:
/home/pi/picam-streamer/lib/server.js 
Thanks for the hard work! Very much appreciated!

**Comment by kerwinf** [comment]
I am starting to use this for a RPi0w and am curious how to set default values at launch. My camera seems to have too much red so all the colors are off. Everything is pinkish purple.

**Comment by iizukanao** [comment]
@jpt000 Sorry, I missed your message!

@kerwinf You might want to set white balance using picam's `--wb <value>` option. You can add picam options by editing line 44 of /home/pi/picam-streamer/lib/server.js like this:

```
    picam = child_process.spawn('nice', ['-n', '-20', 'ionice', '-c1', '-n0', 'sudo', '-u', "#" + PICAM_UID, PICAM_PATH, '--rtspout', '--alsadev', 'hw:1,0', '--wb', 'fluorescent' ], {
```

**Comment by iizukanao** [comment]
See https://github.com/iizukanao/picam#command-options for the list of picam options.

**Comment by TomTomCountry** [comment]
You have done a really great job. I finally got my picam running after trying for some weeks in my freetime. But I still struggle to rotate the picture. I have added the '--rotation 180' to the server.js file, but it seems not working. I even tried to put it in brackets <>.
So I will be thankful for any tip ;-)
And maybe some very basics for the most, but how can I restart picam-streamer via ssh without rebooting?
Thanks in advandce

**Comment by iizukanao** [comment]
@TomTomCountry Hi, thanks for using picam-streamer!
`sudo service picam-streamer restart` will do the job!

**Comment by iizukanao** [comment]
As for rotation, could you share the line you have edited?

**Comment by TomTomCountry** [comment]
Hi @iizukanao sure,
here is the line for the rotation
`picam = child_process.spawn('nice', ['-n', '-20', 'ionice', '-c1', '-n0', 'sudo', '-u', "#" + PICAM_UID, PICAM_PATH, '--rtspout', '--alsadev' , '--rotation 180', 'hw:1,0'], {
`
Thanks for your fast response :)

**Comment by iizukanao** [comment]
@TomTomCountry You have to write `'--rotation', '180'` instead of `'--rotation 180'`. Also, there must be `'hw:1,0'` right after `'--alsadev'`, so put `'--rotation', '180'` at the very end of the arguments.
```js
picam = child_process.spawn('nice', ['-n', '-20', 'ionice', '-c1', '-n0', 'sudo', '-u', "#" + PICAM_UID, PICAM_PATH, '--rtspout', '--alsadev', 'hw:1,0', '--rotation', '180'], {
```
