### ISSUE TITLE
how to change the location of the 'archive', (picam-streamer/archive) directory to a attached pendrive (viz /media/usb/archive)

### ISSUE THREAD

**Issue by rajeshkrarora1** [iizukanao/picam-streamer#45]
Hi sir, Thank you for this wonderful project.
I need to change the  'picam-streamer/archive' to a directory in the attached usb drive, I want to directly save the recorded videos on a attached USB pendrive, please help me with that

**Comment by rajeshkrarora1** [comment]
Sir, I'am using ur script in "https://github.com/iizukanao/picam/issues/89" for recording, is it possible to write a script to check and 'mv' all the video files in "picam-streamer/archive", viz "picam-streamer/archive/*.ts "  to a folder in mounted USB drive to raspberry pi continuously and also maintain a circular buffer of recording

**Comment by iizukanao** [comment]
Hi @rajeshkrarora1,
Apologies for the delayed response. Yes, you can replace the *archive* directory with a symbolic link in order to store recorded files into somewhere else. If you mount a USB drive at */mnt/mydisk*, run these commands:

```sh
sudo service picam-streamer stop
mv /home/pi/picam-streamer/archive/* /mnt/mydisk/
rmdir /home/pi/picam-streamer/archive
ln -s /mnt/mydisk /home/pi/picam-streamer/archive
sudo service picam-streamer start
```

**Comment by rajeshkrarora1** [comment]
Hi Sir, Thank you for your response. This is working like magic now. 🙏🙏

**Comment by iizukanao** [comment]
Great, thanks for the feedback! 🙂
