### ISSUE TITLE
picam-streamer has stopped working after upgrading to node.js version 12 or 14

### ISSUE THREAD

**Issue by rajeshkrarora1** [iizukanao/picam-streamer#46]
Hi Sir, I was using node-red with picam-streamer, it was working wonderfully up till now , i had to upgrade node.js as node-red dropped support to  node.js  version 10 and below, dashboard nodes after upgrading the stream at the time of boot stopped completely, i tried to start it by giving command "sudo /etc/init.d/picam-streamer start", it gives an out put,

Starting picam-streamer
creating directory structure...
starting node-rtsp-rtmp-server and picam...
nohup: redirecting stderr to stdout
nohup: failed to run command '/usr/local/bin/node': No such file or directory.

**Comment by iizukanao** [comment]
What is the output of the command `which node`?

**Comment by rajeshkrarora1** [comment]
Thankyou for responding so promptly

it pi@raspberrypi:~ $  which node
/usr/bin/node

**Comment by rajeshkrarora1** [comment]
🙏🙏

**Comment by rajeshkrarora1** [comment]
how should i solve this problem, where do i need to edit the path

**Comment by iizukanao** [comment]
You can just run `sudo ln -s /usr/bin/node /usr/local/bin/node` and the problem will be fixed.

**Comment by rajeshkrarora1** [comment]
Thankyou so so very much, for your support 🙏🙏🙏🙏

**Comment by iizukanao** [comment]
You're welcome 🙂
