### ISSUE TITLE
raw A/V output on HDMI port

### ISSUE THREAD

**Issue by rajeshkrarora1** [iizukanao/picam-streamer#51]
Hi Iizukanao,
Is it possible to get a raw a/v output of picam-streamer on raspberry pi's HDMI port

Thanks and Regards

**Comment by iizukanao** [comment]
If you use the `-p` (or `--preview`) option, the video will be output over HDMI, but the audio will not.

**Comment by rajeshkrarora1** [comment]
Thakyou for your prompt reply

🙏🙏🙏🙏🙏🙏
