### ISSUE TITLE
picam-streamer starts at boot, even if there is no wifi

### ISSUE THREAD

**Issue by rajeshkrarora1** [iizukanao/picam-streamer#54]
Hi iizukanao, is it possible to start audio/video recording at boot, even if there is no wifi signal, I tried to run a cron job for that but the picam does not start, so no recording happens
Thanks and regards
Rajesh kumar

**Comment by iizukanao** [comment]
picam does not depend on WiFi availability. Is it possible to collect some logs of why picam does not start?

**Comment by rajeshkrarora1** [comment]
Hi iizukanao, Thanks, I used picam instead of picam-streamer and the issue got resolved
