### ISSUE TITLE
using picam-streamer for audio only streaming and recording

### ISSUE THREAD

**Issue by rajeshkrarora1** [iizukanao/picam-streamer#55]
Hi Iizukanao, is there a way to start picam or picam-streamer for audio only streaming and recording

Thanks and Regards
Rajesh kumar

**Comment by iizukanao** [comment]
Hi Rajesh,

Unfortunately, picam does not support audio-only streaming as it's primarily a tool for video streaming. I would recommend using ffmpeg instead.

**Comment by rajeshkrarora1** [comment]
Thanks for a prompt response🙏🙏🙏🙏
