### ISSUE TITLE
not working

### ISSUE THREAD

**Issue by bebsico** [iizukanao/picam-streamer#6]
i dd-ed the 2016-09-05-picam-streamer-1.4.3.img onto an sd card and it boots just fine. i can ssh into the pi. but nothing at http://raspberrypi.local/view/ and neither node nor picam are running. 

what could i be doing wrong?

**Comment by iizukanao** [comment]
@todoistobe Did you check MD5 or SHA256 sums of the downloaded file?

If it's OK, is your Raspberry Pi Camera properly connected? To see if it's working, SSH into your Pi and stop the service with `sudo service picam-streamer stop`, then try using `raspivid`.

**Comment by bebsico** [comment]
okay, the problem: camera connection. i disconnected and reconnected the camera module and now it works like a charm!

thanks!
