### ISSUE TITLE
4 channel microphone

### ISSUE THREAD

**Issue by MichaelAronsen** [iizukanao/picam-streamer#9]
Hi,

Nice job on this project, works very well.

Only issue I have is, I use a ps3 eye webcam for microphone, as it has a 4 channel microphone array, giving very good sensitivity (baby cam, good to hear every little squeek :)).

But this does not work with picam, any possibility of getting it to work?

**Comment by iizukanao** [comment]
Unfortunately, picam-streamer does not support USB cameras.

**Comment by iizukanao** [comment]
@MichaelAronsen Can you record that audio with `arecord` command?

**Comment by MichaelAronsen** [comment]
Right, so i'm using the pi camera module for video.

I can record audio from the webcam with arecord, yes.

4 channels, 16000Hz and SB16_LE format.

**Comment by iizukanao** [comment]
@MichaelAronsen Oh, that's good to know. I think I can add support for 4-channel audio. Does ps3 eye microphone also support 2-channel audio? If yes, is 2-channel already working with picam?

**Comment by TomUser1** [comment]
whether there can be a problem in it?  : 
"$arecord -D mic_sv  -r 44100 -f S16_LE -t wav -d 0 -c 2  test.wav
Recording WAVE 'test.wav' : Signed 16 bit Little Endian, Rate 44100 Hz, Stereo
arecord: set_params:1233: Sample format non available
Available formats:
- S32_LE"

Сan you add support of the S32_LE FORMAT ALSO sample_fmt=AV_SAMPLE_FMT_S16. 
Thanks

**Comment by leomen3** [comment]
@iizukanao, excellent tool, thank you for the contribution!
One Issue I have encountered:  when using RPi3 4 microphone HAT (http://wiki.seeedstudio.com/ReSpeaker_4_Mic_Array_for_Raspberry_Pi/), is that picam cannot start audio capture:
$ _./picam --alsadev hw:1,0_

> configuring devices
> error: cannot set channel count for microphone (Invalid argument)

**Comment by iizukanao** [comment]
@leomen3 Can you try adding `-c 4` to the command line arguments?
i.e. `$ ./picam --alsadev hw:1,0 -c 4`

**Comment by leomen3** [comment]
@iizukanao , thank you for prompt response.
From picam help, I though only 1 or 2 are a valid parameters.
I tried 4 in any case, and got the below:

> error: invalid channels: 4 (must be 1 or 2)
I am using picam version 1.4.7.

**Comment by iizukanao** [comment]
@leomen3 Since this is actually picam's issue, not picam-streamer, let's move to new issue page I've created. https://github.com/iizukanao/picam/issues/113

I'm closing this issue.
